# Generated by Django 5.0.3 on 2024-04-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height_inches', models.IntegerField()),
                ('weight', models.FloatField()),
                ('target_weight', models.FloatField()),
                ('frequency', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
            ],
        ),
    ]
